-- MySQL Script generated by MySQL Workbench
-- Fri Nov 12 11:05:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jr_blog
-- -----------------------------------------------------
-- 博客系统库
DROP SCHEMA IF EXISTS `jr_blog` ;

-- -----------------------------------------------------
-- Schema jr_blog
--
-- 博客系统库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jr_blog` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `jr_blog` ;

-- -----------------------------------------------------
-- Table `jr_blog`.`blog_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jr_blog`.`blog_user` ;

CREATE TABLE IF NOT EXISTS `jr_blog`.`blog_user` (
  `id` BIGINT(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL COMMENT '邮箱，作为登录账号',
  `password` VARCHAR(64) NOT NULL COMMENT '密码',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '标志位，默认为0，表示用户存在',
  `nick_name` VARCHAR(20) NOT NULL DEFAULT '新用户' COMMENT '昵称，显示的用户名',
  `avatar_img_url` VARCHAR(120) NOT NULL DEFAULT '' COMMENT '头像图片url',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '博客用户表';


-- -----------------------------------------------------
-- Table `jr_blog`.`blog_article_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jr_blog`.`blog_article_record` ;

CREATE TABLE IF NOT EXISTS `jr_blog`.`blog_article_record` (
  `id` BIGINT(20) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT current_timestamp,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态位,-1为已删除，0为草稿，1为已发表(所有人可看)，2为私密(只有自己可看)',
  `fr_user_id` BIGINT(20) NOT NULL COMMENT '外键，该文章所属用户',
  `article_title` VARCHAR(100) NOT NULL COMMENT '文章标题，长度小于100',
  `article_summary` VARCHAR(200) NOT NULL COMMENT '文章摘要',
  `fr_article_id` CHAR(26) NOT NULL COMMENT '外键，文章内容在其他表',
  `comment_count` INT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论数',
  `visit_count` INT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '点击量',
  `fr_category_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '文章所属分类id',
  `likes_count` INT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '点赞数',
  `oppose_count` INT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '反对数',
  `priority` INT(20) UNSIGNED NOT NULL DEFAULT 1 COMMENT '排序（小到大），0表示置顶',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '博客系统，文章记录表';


-- -----------------------------------------------------
-- Table `jr_blog`.`blog_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jr_blog`.`blog_category` ;

CREATE TABLE IF NOT EXISTS `jr_blog`.`blog_category` (
  `id` BIGINT(20) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT current_timestamp,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `fr_user_id` BIGINT(20) NOT NULL COMMENT '外键，用户id',
  `category_name` VARCHAR(50) NOT NULL DEFAULT 'default category' COMMENT '分类名字',
  `category_desc` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '描述信息',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '文章分类表，一个用户多个分类，一个分类下有多个文章';


-- -----------------------------------------------------
-- Table `jr_blog`.`dict_key`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jr_blog`.`dict_key` ;

CREATE TABLE IF NOT EXISTS `jr_blog`.`dict_key` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `create_time` DATETIME NOT NULL DEFAULT current_timestamp,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态位，默认为0表示存在，1表示已删除',
  `key_name` VARCHAR(20) NOT NULL DEFAULT '其他',
  `desc` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '描述信息',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '字典表key';


-- -----------------------------------------------------
-- Table `jr_blog`.`dict_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jr_blog`.`dict_value` ;

CREATE TABLE IF NOT EXISTS `jr_blog`.`dict_value` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `create_time` DATETIME NOT NULL DEFAULT current_timestamp,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `value_name` VARCHAR(45) NOT NULL DEFAULT '',
  `desc` VARCHAR(45) NOT NULL DEFAULT '',
  `fr_key_id` INT UNSIGNED NOT NULL COMMENT '外键，key_id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '字典表value';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
