server:
  port: 8082
  servlet:
    context-path: /ap

spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.108.238.134:3306/jr_blog?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: My$04-22-287=SQL
#    druid:
#      initial-size: 3
#      min-idle: 3
#      max-active: 7
#      max-wait: 60000
  profiles:
    active: dev

#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.liang.apblog.model.pojo
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl