server:
  port: 8082
  servlet:
    context-path: /ap

blog:
  cors:
    # 跨域设置，前端请求地址
    allowed-origins: http://localhost:8080, http://localhost:8081

  # 管理员账号，暂定这里的账号为管理员，权限部分以后考虑
  admin: 1097578346@qq.com, 627429765@qq.com

spring:
  #  datasource:
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://47.108.238.134:3306/jr_blog?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
  #    username: root
  #    password: My$04-22-287=SQL
  #    druid:
  #      initial-size: 3
  #      min-idle: 3
  #      max-active: 7
  #      max-wait: 60000
  profiles:
    active: dev

#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.liang.apblog.model.pojo
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


